### ISSUE TITLE
'habitat_sim._ext.habitat_sim_bindings.RLRAudioPropagationChannelLayout' object has no attribute 'channelType'

### ISSUE THREAD

**Issue by sreeharshaparuchur1** [facebookresearch/rlr-audio-propagation#13]
Hi,

My use case for this project is with respect to the Soundspaces 2.0 simulator. As a result, I have followed the setup instructions present [in the soundspaces readme](https://github.com/facebookresearch/sound-spaces/blob/main/README.md?plain=1#L42).

I am able to run the example notebook and script given [in the example section of the soundspaces repo](https://github.com/facebookresearch/sound-spaces/tree/main/examples) successfully. However, in multiple places such as in [habitat-labs test audio_agent script](https://github.com/facebookresearch/habitat-sim/blob/main/examples/tutorials/audio_agent.py#L42) and (soundspaces' continuous simulator)[https://github.com/facebookresearch/sound-spaces/blob/main/soundspaces/continuous_simulator.py#L124], the below API call is made to create a channel layout object. 

```
channel_layout = habitat_sim.sensor.RLRAudioPropagationChannelLayout() 
```

On calling the above method, we have to add a sensor object to the channelType attribute, but, this fails for me with my current setup and I get the aforementioned error. In order to provide an error log, I have run ```python scripts/interactive_demo.py CONTINUOUS True``` in my soundspaces 2.0 installation and get the following traceback:

```
Traceback (most recent call last):
  File "scripts/interactive_demo.py", line 245, in <module>
    main()
  File "scripts/interactive_demo.py", line 235, in main
    env = AudioNavRLEnv(config=config, dataset=dataset)
  File "/home/crashtappen/SoundSpaces20/sound-spaces/ss_baselines/common/environments.py", line 48, in __init__
    super().__init__(self._core_env_config, dataset)
  File "/home/crashtappen/SoundSpaces20/habitat-lab-0.2.2/habitat/core/env.py", line 374, in __init__
    self._env = Env(config, dataset)
  File "/home/crashtappen/SoundSpaces20/habitat-lab-0.2.2/habitat/core/env.py", line 105, in __init__
    id_sim=self._config.SIMULATOR.TYPE, config=self._config.SIMULATOR
  File "/home/crashtappen/SoundSpaces20/habitat-lab-0.2.2/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/home/crashtappen/SoundSpaces20/sound-spaces/soundspaces/continuous_simulator.py", line 111, in __init__
    self.add_acoustic_config()
  File "/home/crashtappen/SoundSpaces20/sound-spaces/soundspaces/continuous_simulator.py", line 128, in add_acoustic_config
    channel_layout.channelType = habitat_sim.sensor.RLRAudioPropagationChannelLayoutType.Binaural
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.RLRAudioPropagationChannelLayout' object has no attribute 'channelType'
```
## Current workaround:

I am able to workaround this problem by directly adding the channel configuration to the audio as done in [this example](https://github.com/facebookresearch/sound-spaces/blob/main/examples/soundspaces2_quick_tutorial.ipynb).

Since there is a workaround, this isn't a time critical error but it would help me and the community if you could either update the codes to use the workaround or fix the API.

Thank you

**Comment by ChanganVR** [comment]
@sreeharshaparuchur1 the APIs have been updated and I've updated a [step-by-step installation guide](https://github.com/facebookresearch/sound-spaces/blob/main/INSTALLATION.md), and you could also find examples for setting APIs in this [file](https://github.com/facebookresearch/sound-spaces/blob/main/examples/minimal_example.py).

**Comment by sreeharshaparuchur1** [comment]
@ChanganVR Thank you very much for taking the time out to update the APIs, that should fix this issue.

On going through the changes that you've made and the step-by-step installation guide, I have a doubt about what the line ``` audio_sensor_spec.enableMaterials = False ``` does to:

* Prevent crashing of the audio simulator
* Isn't the RIR computed between two points based on the properties of the materials present in the scene? So wouldn't setting this parameter to false mean a less accurate representation of the audio signature received by the agent and thus poor sim2real transfer?

**Comment by ChanganVR** [comment]
@sreeharshaparuchur1 you are right, setting the parameter to not use materials leads to suboptimal performance. But for some environments, if the semantic annotations are faulty, using materials simply does not render and leads to crashing every time. If the semantic annotation issue can't be fixed, you could consider disabling using materials.
